
jobs:
- ${{ each target in parameters.targets }}:
  - ${{ each compiler in parameters.compilers }}:
    - ${{ each backend in parameters.backends }}:
      - job:
        displayName: "${{ format('Linux  {0}  {1}  {2}', target, compiler, backend) }}"
        pool:
          vmImage: 'ubuntu-20.04'
        steps:
          - script:
              set -ex

              sudo apt-get update && sudo apt-get -y install --no-install-recommends build-essential g++-10 clang++-10 liballegro4-dev libsdl1.2-dev libsdl-mixer1.2-dev libsdl2-dev libsdl2-mixer-dev zlib1g-dev libbz2-dev libpng-dev

              ${{ compiler }} BACKEND=${{ backend }} make -j$(nproc) ${{ target }}
