
jobs:
  - ${{ each image in parameters.images }}:
    - ${{ each arch in parameters.archs }}:
      - ${{ each buildConfig in parameters.buildConfigs }}:
        - job:
          displayName: "${{ format('{0}  {1}  {2}', image, arch, buildConfig) }}"
          pool:
            vmImage: ${{ image }}
          steps:
            - template: download-deps.yml
              parameters:
                depsVersion: '4'
                depsTriplet: ${{ format('{0}-windows-static', arch) }}
            - task: VSBuild@1
              displayName: 'Build'
              inputs:
                solution: 'Simutrans-Extended.sln'
                ${{ if eq(arch, 'x86') }}:
                  platform: "Win32"
                ${{ if ne(arch, 'x86') }}:
                  platform: ${{ arch }}
                configuration: ${{ buildConfig }}
                msbuildArgs: '/t:"Simutrans-Extended"'
                maximumCpuCount: true
