
jobs:
- ${{ each project in parameters.projects }}:
  - ${{ each image in parameters.images }}:
    - ${{ each arch in parameters.archs }}:
      - ${{ each buildConfig in parameters.buildConfigs }}:
        - job:
          displayName: "${{ format('{0}  {1}  {2}  {3}', project, image, arch, buildConfig) }}"
          pool:
            vmImage: ${{ image }}
          steps:
            - template: download-deps.yml
              parameters:
                depsVersion: '5'
                depsTriplet: ${{ format('{0}-windows-static', arch) }}
            - task: VSBuild@1
              displayName: 'Build'
              inputs:
                solution: 'Simutrans-Extended.sln'
                platform: ${{ arch }}
                configuration: ${{ buildConfig }}
                msbuildArgs: "${{ format('/t:{0}', project) }}"
                maximumCpuCount: true
